name: CI

on:
  push:
    branches: [ develop, release/**, main, master, feature/**, issue/**, issues/**, dependabot/** ]

env:
  NODE_VERSION: "18.x"
  PYTHON_VERSION: "3.11"
  JUPYTERLAB_VERSION: "~=4.1.0"

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: getsentry/action-github-app-token@v3
        name: cicd token
        id: cicd-key
        with:
          app_id: ${{ secrets.CICD_APP }}
          private_key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.cicd-key.outputs.token }}
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install the Python dependencies
        run: |
          python -m pip install --upgrade pip "jupyterlab${{ env.JUPYTERLAB_VERSION }}"
      - name: Build the extension
        run: |
          jlpm install
          pip install -e . -v
          jupyter labextension develop . --overwrite
      - name: Check extension installation
        run: |
          jupyter labextension list 2>&1 | tee labextension.list
          cat labextension.list | grep -ie "maap_algorithms_jupyter_extension.*OK"
      - name: Browser check
        run: |
          python -m jupyterlab.browser_check
